import React from "react";
import Footer from "@/components/home_sections/footer";
import { createAdminUser, createRoles } from "@/utils/initialSetup";

createRoles().then(function () {
    createAdminUser().then()
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
